# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_G6EttqwLrKBChPACN_9Eu5b1ARu0ytu
"""

import yfinance as yf
import pandas_ta as ta

def get_rsi(ticker_symbol):
    # Fetch last 30 days of data (need enough for 14-period RSI)
    data = yf.download(ticker_symbol, period="1mo", interval="1d", progress=False)

    if data.empty:
        return None

    # Calculate RSI using pandas_ta (Standard 14-day period)
    rsi = ta.rsi(data['Close'], length=14)
    return rsi.iloc[-1]

def run_agent():
    tickers = {"S&P 500": "^GSPC", "Mexican IPC": "^MXX"}
    print("--- Daily RSI Report (18:00 UTC) ---")

    for name, ticker in tickers.items():
        rsi_val = get_rsi(ticker)
        if rsi_val is not None:
            status = "NORMAL"
            if rsi_val > 70: status = "OVERBOUGHT ⚠️"
            elif rsi_val < 30: status = "OVERSOLD 🟢"

            print(f"{name} ({ticker}): RSI = {rsi_val:.2f} | Status: {status}")
        else:
            print(f"Could not retrieve data for {name}")

if __name__ == "__main__":
    run_agent()